#DB
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: 1234
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: hdi

BASE_URL: http://localhost:8080

REDIS_HOST: localhost
REDIS_PORT: 6379
